### ISSUE TITLE
proper emacs/doom theme

### ISSUE THREAD

**Issue by sureyeaah** [tathran/spaceduck-emacs#1]
It would be great if you could take a popular existing emacs/doom-emacs theme and modify that instead of relying on ugly hacks.

**Comment by ghost** [comment]
Hello, 

Thanks for the suggestion. I just updated the `README` to include a todo list. I do plan on creating a proper theme and will likely use a doom emacs theme as you suggested as a base. I made the quick and dirty hacky solution just to get something out there right away.

**Comment by ghost** [comment]
Theme has been updated so no reliance on color/modeline hacks. However, colors are still being worked on. Feel free to contribute :)
